# Generated by Django 4.0.4 on 2022-11-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_maquette_nb_api_maquette_nb_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquette',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
