# Generated by Django 4.0.4 on 2022-11-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_alter_maquette_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquette',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
