# Generated by Django 4.0.4 on 2022-11-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_alter_maquette_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquette',
            name='image',
        ),
    ]
